package com.boss.bes.paper.exception;

/**
 * @Author: wangziyi
 * @program: com.boss.bes.paper.exception
 * @Description:
 * @Date: 2020/7/10 9:14
 * @since: 1.0
 */
public enum PaperExceptionCode {

    /**
     * 试卷服务异常
     */
    PAPER_CENTER_MAKE_PAPER_PAPER_INSERT_ERROR("220101", "试卷插入失败！"),
    PAPER_CENTER_MAKE_PAPER_SUBJECT_INSERT_ERROR("220102","试卷试题插入失败"),
    PAPER_CENTER_MAKE_PAPER_ANSWER_INSERT_ERROR("220103","试题答案插入失败"),
    PAPER_CENTER_MAKE_PAPER_SUBJECT_NOT_FOUND_ERROR("230104","未找到符合条件的题目，请重新配置"),
    PAPER_CENTER_QUICK_MAKE_PAPER_ERROR("220105", "快速组卷失败！"),
    PAPER_CENTER_STAND_MAKE_PAPER_ERROR("220106", "标准组卷失败！"),



    PAPER_CENTER_PAPER_UPLOAD_TEMPLATE_INSERT_ERROR("220201","模板记录插入失败"),
    PAPER_CENTER_PAPER_UPLOAD_TEMPLATE_SUBJECT_INSERT_ERROR("220202","模板试题插入失败"),
    PAPER_CENTER_PAPER_UPLOAD_TEMPLATE_ANSWER_INSERT_ERROR("220203","模板试题答案插入失败"),
    PAPER_CENTER_PAPER_UPLOAD_PAPER_NOT_FOUND_ERROR("220204","上传试卷卷未找到"),
    PAPER_CENTER_PAPER_UPLOAD_TEMPLATE_ENAME_EXIST_ERROR("220205","模板名已存在"),
    PAPER_CENTER_PAPER_UPLOAD_PAPER_NOT_NO_UN_UPLOAD_ERROR("220206","试卷状态不为未上传"),


    PAPER_CENTER_PAPER_DOWNLOAD_PAPER_INSERT_ERROR("220301","试卷记录插入失败"),
    PAPER_CENTER_PAPER_DOWNLOAD_PAPER_SUBJECT_INSERT_ERROR("220302","试卷试题插入失败"),
    PAPER_CENTER_PAPER_DOWNLOAD_PAPER_ANSWER_INSERT_ERROR("220303","试卷试题答案插入失败"),
    PAPER_CENTER_PAPER_DOWNLOAD_TEMPLATE_NOT_FOUND_ERROR("220304","下载模板未找到"),
    PAPER_CENTER_PAPER_DOWNLOAD_PAPER_ENAME_EXIST_ERROR("220305","试卷名已存在"),
    PAPER_CENTER_PAPER_DOWNLOAD_TEMPLATE_DISENABLE_ERROR("220306","模板被禁用"),


    PAPER_CENTER_PAPER_MANAGE_DELETE_PAPER_ERROR("220401","删除单份试卷失败"),
    PAPER_CENTER_PAPER_MANAGE_DELETE_PAPERS_ERROR("220402","删除多份试卷失败"),
    PAPER_CENTER_PAPER_MANAGE_VERSION_ERROR("220403","数据版本校验失败或数据已被修改，请刷新后修改"),
    PAPER_CENTER_PAPER_MANAGE_PAPER_MODIFY_ERROR("220404","试卷修改失败"),
    PAPER_CENTER_PAPER_MANAGE_SUBJECT_MODIFY_ERROR("220405","试卷试题修改失败"),
    PAPER_CENTER_PAPER_MANAGE_ANSWER_MODIFY_ERROR("220406","试题答案修改失败"),
    PAPER_CENTER_PAPER_MANAGE_ANSWER_DELETE_ERROR("220407","答案删除失败"),
    PAPER_CENTER_PAPER_MANAGE_SUBJECT_DELETE_ERROR("220408","试题删除失败"),
    PAPER_CENTER_PAPER_MANAGE_SUBJECT_ADD_ERROR("220409","试题添加失败"),
    PAPER_CENTER_PAPER_MANAGE_ANSWER_ADD_ERROR("220410","答案添加失败"),
    PAPER_CENTER_PAPER_MANAGE_IMAGE_UPLOAD_ERROR("220411","图片上传失败"),
    PAPER_CENTER_PAPER_MANAGE_IMAGE_DELETE_ERROR("220412","图片删除失败"),
    PAPER_CENTER_PAPER_MANAGE_PAPER_NAME_EXIST_ERROR("220413","试卷名已经存在"),
    PAPER_CENTER_PAPER_MANAGE_PAPER_VERSION_ERROR("220414","删除失败，数据已被修改"),
    PAPER_CENTER_PAPER_MANAGE_IMAGE_DEAL_ERROR("220415","图片处理失败"),
    PAPER_CENTER_PAPER_MANAGE_PAPER_STATUS_MODIFY_ERROR("220416","试卷状态修改失败"),
    PAPER_CENTER_PAPER_MANAGE_PAPER_NOT_MODIFY_ERROR("220417","试卷正在被编辑，请稍候尝试"),
    PAPER_CENTER_PAPER_MANAGE_ANSWER_NOT_FOUND_ERROR("220418","待修改的答案不存在"),
    PAPER_CENTER_PAPER_MANAGE_SUBJECT_NOT_FOUND_ERROR("220419","待修改的试题不存在"),
    PAPER_CENTER_PAPER_MANAGE_PAPER_NOT_FOUND_ERROR("220420","待修改的试卷不存在"),




    PAPER_CENTER_GET_BASEDATA_SERVICE_GET_SUBJECT_TYPE_ERROR("220501","调用基础数据服务获取题型失败"),
    PAPER_CENTER_GET_BASEDATA_SERVICE_GET_CATEGORY_ERROR("220502","调用基础数据服务获取题目类别识别"),
    PAPER_CENTER_GET_BASEDATA_SERVICE_GET_CONFIG_LIST_ERROR("220503","调用基础数据服务获取配置列表失败"),
    PAPER_CENTER_GET_BASEDATA_SERVICE_GET_CONFIG_ITEM_ERROR("220504","调用基础数据服务获取配置详细项失败"),
    PAPER_CENTER_GET_BASEDATA_SERVICE_QUICK_MAKE_PAPER_ERROR("220505","调取基础数据服务进行快速组卷失败"),
    PAPER_CENTER_GET_BASEDATA_SERVICE_STANDARD_MAKE_PAPER_ERROR("220506","调取基础数据服务进行标准组卷失败"),

    PAPER_CENTER_GET_SYSTEM_SERVICE_GET_DICTIONARY_ERROR("220601","调取系统管理服务获取字典数据失败"),
    PAPER_CENTER_PUBLIC_FIELD_FILL_ERROR("220602","公共字段填充失败"),
    PAPER_CENTER_PROPERTY_TRANSFER_ERROR("220603","参数转换失败"),
    PAPER_CENTER_PROPERTY_TRANSFER_NOT_MATCH_ERROR("220604","参数转换未匹配");


    /**
     * 异常码
     */
    private final String code;
    /**
     * 异常信息
     */
    private final String message;

    PaperExceptionCode(String code, String message) {
        this.code = code;
        this.message = message;
    }

    public String getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }


    }
