spring:
  mail:
    host: smtp.163.com
    username: boss_exam_g02@163.com
    password: PILVKBEBYDFXKYUW
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttles:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

